### PR TITLE
Switch to json_serializable for Dart 2 compatibility

### PR DESCRIPTION
**Pull request by chances**
- [Dart 2 JSON Support](https://www.dartlang.org/guides/json)
- [json_serializable](https://pub.dartlang.org/packages/json_serializable)

I was experiencing issues in my Flutter installation related to agilord/owl#4

I also updated the README with instructions for rebuilding JSON models.

### CODE REVIEW

**Comment by chances** [comment]
@rinukkusu Huh, Travis is saying:

```
Package build_runner has no versions that match >=0.8.10 <0.9.0 derived from:
- spotify depends on version ^0.8.10
```

But [that version](https://pub.dartlang.org/packages/build_runner#-changelog-tab-) exists...

Does some Travis cache need cleaning, perhaps?

**Comment by rinukkusu** [comment]
I think this has to do with the Dart SDK constraints from the `json_serializable` and `build_runner` packages. Running [`mediator`](https://github.com/thosakwe/pub_mediator) yields:

```
✗ Found 1 dependency conflict:
You are running Dart SDK version 1.24.3 (Mon Dec 18 16:57:48 2017) on "linux_x64".
  * spotify requires SDK >=1.20.1 <2.0.0
  * json_annotation requires SDK >=2.0.0-dev.54.0 <2.0.0
  * json_serializable requires SDK >=2.0.0-dev.54 <2.0.0
  * http requires SDK >=2.0.0-dev.61.0 <3.0.0
  * build_runner requires SDK >=2.0.0-dev.54 <2.0.0
  * test requires SDK >=2.0.0-dev.54.0 <2.0.0
  * json_serializable->path requires SDK >=2.0.0-dev.62.0 <2.0.0
  * json_serializable->source_gen requires SDK >=2.0.0-dev.19.0 <2.0.0
  * test->async requires SDK >=2.0.0-dev.23.0 <2.0.0
  * build_runner->dart_style requires SDK >=2.0.0-dev.62.0 <2.0.0
  * json_serializable->build requires SDK >=2.0.0-dev.9 <2.0.0
  * build_runner->build_config requires SDK >=2.0.0-dev.54 <2.0.0
  * http->collection requires SDK >=2.0.0-dev.55.0 <2.0.0
  * build_runner->build_runner_core requires SDK >=2.0.0-dev.54 <2.0.0
  * build_runner->build_resolvers requires SDK >=2.0.0-dev.32 <2.0.0
  * build_runner->shelf requires SDK >=2.0.0-dev.61.0 <2.0.0
  * build_runner->mime requires SDK >=2.0.0-dev.20.0 <2.0.0
  * test->matcher requires SDK >=2.0.0-dev.17.0 <2.0.0
  * build_runner->stream_transform requires SDK >=2.0.0-dev.20.0 <2.0.0
  * build_runner->pool requires SDK >=2.0.0-dev.17.0 <2.0.0
  * test->io requires SDK >=2.0.0-dev.54 <3.0.0
  * test->shelf_web_socket requires SDK >=2.0.0-dev.17.0 <2.0.0
  * test->http_multi_server requires SDK >=2.0.0-dev.55.0 <3.0.0
  * test->boolean_selector requires SDK >=2.0.0-dev.58 <3.0.0
  * test->source_maps requires SDK >=2.0.0-dev.17.0 <2.0.0
  * json_serializable->analyzer requires SDK >=2.0.0-dev.48.0 <2.0.0
  * build_runner->crypto requires SDK >=2.0.0-dev.17.0 <3.0.0
  * build_runner->code_builder requires SDK >=2.0.0-dev <2.0.0
  * build_runner->yaml requires SDK >=2.0.0-dev.49.0 <2.0.0
  * test->package_resolver requires SDK >=2.0.0-dev.17.0 <2.0.0
  * build_runner->watcher requires SDK >=2.0.0-dev.61.0 <2.0.0
  * build_runner->build_config->pubspec_parse requires SDK >=2.0.0-dev.54 <2.0.0
  * test->shelf_web_socket->web_socket_channel requires SDK >=2.0.0-dev.23.0 <2.0.0
  * test->vm_service_client requires SDK >=2.0.0-dev.58.0 <2.0.0
  * json_serializable->analyzer->kernel requires SDK >=2.0.0-dev.48.0 <2.0.0
  * json_serializable->analyzer->html requires SDK >=2.0.0-dev.17.0 <2.0.0
  * test->stream_channel requires SDK >=2.0.0-dev.17.0 <2.0.0
  * build_runner->code_builder->built_collection requires SDK >=2-0-0-dev <2.0.0
  * build_runner->code_builder->built_value requires SDK >=2.0.0-dev <2.0.0
  * test->shelf_packages_handler->shelf_static requires SDK >=2.0.0-dev.61.0 <3.0.0
  * json_serializable->analyzer->html->utf requires SDK >=2.0.0-dev.20.0 <2.0.0
  * json_serializable->analyzer->html->csslib requires SDK >=2.0.0-dev.17.0 <2.0.0
  * test->vm_service_client->json_rpc_2 requires SDK >=2.0.0-dev.17.0 <2.0.0
  * json_serializable->analyzer->front_end requires SDK >=2.0.0-dev.48.0 <2.0.0
Done at 2018-07-14 10:56:15.272476.
```

So i guess we need to switch to the dev channel in the `.travis.yml` file.

**Comment by chances** [comment]
Well, owl supposedly [works with Dart 2 now](https://github.com/agilord/owl/issues/4#issuecomment-405257634)... I haven't gotten around to testing that yet.

Now I'm not sure this port was _entirely_ necessary. Though, [json_serializable](https://pub.dartlang.org/packages/json_serializable) does have greater ecosystem reach not to mention more Google folks backing it.

Why did you decide to go with owl in the first place?

**Comment by rinukkusu** [comment]
When I started with this project I wasn't aware of `json_serializable` and I had already worked with `owl` on other projects, so this was my choice 😄 

But I don't mind using `json_serializable` as well - seems like it's not that scary anymore.

**Comment by hayribakici** [comment]
@rinukkusu just out of curiosity, is the PR going to merged soon? It would be nice, to get this library working with `Dart 2`.

**Comment by rinukkusu** [comment]
Hi @hayribakici, it's merged and published - sorry for the wait :smile_cat:

**Pull request merged**
