### PR TITLE
fix: spotify sending double instead of int for documented endpoints

### PR DESCRIPTION
**Pull request by KRTirtho**
Extending @hayribakici fix, I applied the same `convertToInIfDoubleValue` for all `int` and `int?` type properties across the library just to be future-proof 😅  

Currently, it's happening for the following endpoints:

- album/tracks, 
- artists, (fixed + releases)
- artist, (fixed + releases)
- artist/related-artists (fixed + releases)

### CODE REVIEW

**Comment by KRTirtho** [comment]
Closes #207

**Comment by hayribakici** [comment]
oh man, I thought this wouldn't hunt us anymore 😅

**Review by rinukkusu — APPROVED** [review]
LGTM! Thanks for fixing this!
What are they cooking in the public api department at Spotify? 🤔

**Comment by KRTirtho** [comment]
Proprietary API. Think about the actual paid customers.

**Pull request merged**
