### PR TITLE
Refactor cursor pages

### PR DESCRIPTION
**Pull request by hayribakici**
This PR adds heavy refactoring regarding the Pages-objects

This is a rather a big one...
The goal of this PR is to allow `CursorPages` to have a `stream()` functionality like in `Pages`. So I refactored out a lot of methods and created new classes. The reasons are as following:

Since the `getPage(...)` method exists in `Pages` as well in `CursorPages`, however the signature is not the same. For `Pages` it is `getPage(int limit, int offset)` and for `CursorPages` it is `getPage(int limit, String after)`. In order to respect the method signatures more classes have been added. A diagram of the current design can be found below.

Paging

I am not 100% happy with this approach, as I find it a little over-engineered. What do you guys think?

### CODE REVIEW

**Comment by hayribakici** [comment]
@rinukkusu I was wondering, if this PR could be reviewed in any way. Thank you 😄

**Comment by rinukkusu** [comment]
@hayribakici I have looked at it a few times already (over the months 🥺) and I really like it! Would you mind bringing it up to date with  the master branch? I'm currently in Spain, but I'd love to get back to this repo backlog next week!

**Review by rinukkusu — APPROVED** [review]
LGTM!

@hayribakici but there are still some merge conflicts, it seems :(

**Comment by hayribakici** [comment]
@rinukkusu thanks, I'll take a look :)

**Comment by hayribakici** [comment]
@rinukkusu I don't see any merge conflicts here. Where do you see them?

**Comment by rinukkusu** [comment]
@hayribakici GitHub on Desktop was not letting me merge just before.

**Comment by rinukkusu** [comment]
Worked on mobile lol

**Pull request merged**
