### PR TITLE
Add Categories API

### PR DESCRIPTION
**Pull request by IKatsuba**

### CODE REVIEW

**Comment by ebarnsli** [comment]
cool more PR's, hopefully @rinukkusu will get to these soon :)

**Comment by ebarnsli** [comment]
he trolling us by comitting on sept 7 but ignoring all the PR's lol

**Comment by rinukkusu** [comment]
I'll be home next week with less working hours - will revisit all PRs and Issues then. Sorry for the major letdown, but the circumstances of the last months didn't allow me to invest more time.

**Comment by ebarnsli** [comment]
Awesome. Sorry I was just kinda trolling. Totally get it

**Comment by IKatsuba** [comment]
Any updates?

**Comment by rinukkusu** [comment]
Thank you guys for adding the categories endpoints and sorry for the ridiculously long wait!!!

**Pull request merged**
