### PR TITLE
Create a client using only an AccessToken

### PR DESCRIPTION
**Pull request by fotiDim**
Addresses https://github.com/rinukkusu/spotify-dart/issues/70 by adding a new constructor that only requires a valid access token.

### CODE REVIEW

**Review by rinukkusu — DISMISSED** [review]

**Comment by zommerberg** [comment]
Can this be merged @rinukkusu  ?

**Comment by rinukkusu** [comment]
Not directly, there are still merge conflicts that need to be addressed. If the author doesn't check these, then maybe you want to open another PR and we close this one? :)

**Comment by fotiDim** [comment]
@rinukkusu when I opened the PR there were no conflicts. This PR had been unreviewed for a really long time. It would be nice if you mentioned me when you introduced the conflict so that I was notified that it needed to be fixed.
Closing PRs and copying over code is no way to treat contributors.

**Comment by rinukkusu** [comment]
@fotiDim I know I have not been very active with reviewing the PRs and Issues lately because of personal reasons, sorry! If you care to remove the changelog entry and let me handle releases, then the PR should be good. :)

**Comment by fotiDim** [comment]
@rinukkusu changelog removed. Let's merge this before it gets outdated again.
I can help with PR reviewing. You can add me to the repo as collaborator.

**Review by rinukkusu — APPROVED** [review]

**Review by rinukkusu — CHANGES_REQUESTED** [review]
Hmm, there still seems to be some kind of conflict. :(

**Comment by fotiDim** [comment]
Are you sure? Can't see any conflict on my end.

**Review by rinukkusu — APPROVED** [review]

**Comment by rinukkusu** [comment]
@fotiDim Github thinks so

**Comment by fotiDim** [comment]
@rinukkusu I was able to merge just fine after you approved 🤷‍♂️

**Comment by rinukkusu** [comment]
Interesting, it still showed merge conflicts after approving for me - welp i take it :)

**Pull request merged**
