### PR TITLE
User library & follow endpoint implementations

### PR DESCRIPTION
**Pull request by KRTirtho**
Added support for following endpoints

| Endpoints                                      | Class    | Method           | HTTP method |
|------------------------------------------------|----------|------------------|-------------|
| /v1/me/following/contains                      | Me       | isFollowing      | GET         |
| /v1/me/following                               | Me       | follow           | PUT         |
| /v1/me/following                               | Me       | unfollow         | DELETE      |
| /v1/me/albums                                   | Me       | savedAlbums      | GET         |
| /v1/me/albums                                   | Me       | saveAlbums       | PUT         |
| /v1/me/albums                                   | Me       | removeAlbums     | DELETE      |
| /v1/me/albums/contains                          | Me       | isSavedAlbums    | GET         |
| /v1/playlists/{playlist-id}/followers/contains | Playlists | followedBy       | GET         |
| /v1/me/tracks                                   | TracksMe | remove, removeOne | DELETE      |

Other smaller tweaks/bugfixes:
- Replaced non-required mutable `var` variables with immutable `final`s
-  `Future<Null>` return types replaced with `Future<void>`
- `TracksMe.contains` throws a `TypeError` while casting `List<bool>`
- Tests created for newly added endpoints which are testable

**Note:** The `FollowingType.user` wasn't tested for `Me.follow`/`Me.unfollow` methods

Awesome library dude. Without **spotify-dart**, **spotube** wouldn't be possible. Keep up your awesome work❣️💪🏻

### CODE REVIEW

**Comment by KRTirtho** [comment]
@rinukkusu can I get some update/feedback/review regarding this PR if possible?

**Comment by KRTirtho** [comment]
Can I do that? I don't think I've permissions to edit wiki of a repo which isn't owned by me. But these ones should be checked

# Follow API
- [x] Check If User Follows Artists or Users
- [x] Check if Users Follow a Playlist
- [x] Follow Artists or Users
- [x] Unfollow Artists or Users

# Library API
- [x] Get User's Saved Albums
- [x] Save Albums for Current User
- [x] Remove Albums for Current User
- [x] Check User's Saved Albums
- [x] Remove User's Saved Tracks
- [x] Get User's Saved Tracks
- [x] Save Tracks for User

**Comment by hayribakici** [comment]
Cool, once this is merged, I'll check them for you.

**Review by rinukkusu — APPROVED** [review]
Sorry for being late to the party and thank you for your contribution!
The only thing that doesn't "sound" good is `isSavedAlbums`, but not sure how else to name it, so let's fly with that for now.

**Comment by KRTirtho** [comment]
I also added a Bugfix causing `onCredentialsRefreshed` not getting called when its supposed to
Reasons & explanations:
https://github.com/rinukkusu/spotify-dart/issues/123#issuecomment-1138231777

**Comment by rinukkusu** [comment]
Hmmm, I also saw that you added some stuff, that older PRs also wanted to add, like the `removeOne` on `TracksMe`. My fault for not noticing that and having not a lot of time to process all of this, but generally not that great.

**Pull request merged**
