### PR TITLE
add null check before fromJson to endpoint_base.dart

### LINKED ISSUE #223: Getting "type 'Null' is not a subtype of type 'Map<String, dynamic>'" on missing audio feature
https://api.spotify.com/v1/audio-features?ids=2cs7JxrZ9DxvsfoVI07ayX
return
```json
{
    "audio_features" : [ 
         null
     ]
}
```

This request throws an error at spotify.audioFeatures.list(trackIds):
type 'Null' is not a subtype of type 'Map<String, dynamic>'

### PR DESCRIPTION
**Pull request by bvasya**
Fixes #223  incorrect json returned from spotify for some audio features

https://api.spotify.com/v1/audio-features?ids=2cs7JxrZ9DxvsfoVI07ayX return
```
{
  "audio_features": [
    null
  ]
}
```

### CODE REVIEW

**Comment by hayribakici** [comment]
@bvasya Thanks making the changes. I forgot to mention, that a unit test, that covers this edge case, should also be added. You can check out the `test` folder on how testing works.

**Comment by bvasya** [comment]
@hayribakici I'm not sure I understand how to write a test to handle the return of incorrect data correctly. The tests have been added.

**Comment by hayribakici** [comment]
@bvasya you can keep the `list` and `get`-tests and remove the `error` test. The error handling is already covered, since it is a general thing. What is important is, that this edge is handled, which you already covered.

**Comment by hayribakici** [comment]
@rinukkusu

**Review by rinukkusu — APPROVED** [review]

**Pull request merged**
