### PR TITLE
feat: enable to json for every serializable model

### LINKED ISSUE #212: Enable `createToJson` for the models
In my app, there are many situations where I need to save/cache any response received from Spotify server.
`spotify-dart` providers me the option to instantiate the models from `Json`/`Map`, but the option to converting the models to `Json`/`Map` isn't available. Since, `spotify-dart` uses `JsonSerializable` to achieve serialization, we can simply toggle on the `toJson` method generation.

Also, I'm curious about why `createToJson` is set to false and will be grateful if you let us know.
My guess is dependency size, but dart removes dead/unused code, so that shouldn't be a problem.

### PR DESCRIPTION
**Pull request by KRTirtho**
Closes #212

### CODE REVIEW

**Comment by hayribakici** [comment]
@KRTirtho that's a useful feature! Could you check the CI build for any errors?

**Comment by rinukkusu** [comment]
I think I/we have removed it to lower the warnings and better our dart analyzer score regarding unused code. Of course we can always revisit this topic. Currently I have no hard feelings regarding toJson or not toJson.

**Comment by hayribakici** [comment]
@rinukkusu is it possible to somehow "configure" whether a `toJson` should exist or not?

**Comment by KRTirtho** [comment]
Btw, in case you forgot to check, I fixed the CI issues 👍

**Review by rinukkusu — APPROVED** [review]
Looks good from what I can tell! Thanks for contributing!

**Comment by rinukkusu** [comment]
@KRTirtho released with `v0.13.6`

**Comment by KRTirtho** [comment]
That's great news 🎉 

But, we have a issue with `toJson` of child property not being called by default. `jsonEncode` calls `toJson` on `Object` that are not primitve before calling `toString`, so we don't face any problem. But when we encode json without dart's default, we face the `<Type Name>` is not `Map<String, dynamic>` exception.

As you can see, `.toJson` is not called for `externalUrls` property for `_$$AlbumToJson`
https://github.com/rinukkusu/spotify-dart/blob/1610dfd2aaddef4b76bca230dc923af084346937/lib/src/models/_models.g.dart#L68

Adding following in `build.yaml` fixes the issue
```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
```

I'll create a PR with the simple fix. Sorry for the trouble, I didn't know this issue until I used Hive to cache some responses.
Tbh, `explicit_to_json` should've been true by default. Not sure why it's turned off in the first place

**Pull request merged**
