### PR TITLE
DRAFT: Add support for Implicit Grant and Authorization Code auth flows

### PR DESCRIPTION
**Pull request by chances**
I needed support for the Authorization Code auth flow for my app, so I've modified the `TokenRequest` and `SpotifyApiCredentials` classes.

I haven't finished implementing the refresh sequence for Authorization Code grants, but I wanted to start getting your review.

### CODE REVIEW

**Comment by chances** [comment]
@rinukkusu Does your Travis configuration support testing this, even if only the Client Credentials grant type? You could store the Spotify API key and secret as environment variables in the Travis web UI.

I can write some tests for that case of you'd like.

**Comment by rinukkusu** [comment]
I'll look through the token renewal process tomorrow.

Regarding the testing I added two environment variables `CLIENT_ID` and `CLIENT_SECRET`. Every file ending with `*test` in the `test` folder gets picked up by `pub run test` automatically iirc.

**Comment by chances** [comment]
The test fails on Travis because it can't find the credentials environment variables. :confused:

**Comment by rinukkusu** [comment]
Interesting ... I looked into the problem and it seems the env vars get removed on PR builds for ["security reasons"](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions).

[A build I triggered from master](https://travis-ci.org/rinukkusu/spotify-dart/builds/340407215#L420) vs [a build triggered from your PR](https://travis-ci.org/rinukkusu/spotify-dart/builds/340291424#L241)

So if that test runs successfully on your machine, then we can check it later on the merge.

**Comment by rinukkusu** [comment]
Hey @chances, I know it's been quite some time, but did the tests run successfully on your local machine?

**Comment by chances** [comment]
@rinukkusu IIRC, the tests did run successfully on my machine.

Though, this PR is pretty outdated. I'll try to make time within the next week to merge in updates from master and confirm the tests pass on my machine.

**Comment by jifalops** [comment]
Has anyone tried this? I need auth code flow in my app

**Comment by rinukkusu** [comment]
I'll close this PR, since we now have a working implementation of the implicit grant flow! 😸

**Pull request closed without merging**
