### PR TITLE
[please merge] Shuffle and Player endpoint

### PR DESCRIPTION
**Pull request by hayribakici**
This PR adds a `me/player/shuffle` and a `me/player` endpoint. 

In particular, since `shuffle` changes the user's current playback, this method is doing 2 requests:
1. the shuffle itself (a `PUT` request) and 2. retrieves the current `player` state with its updated information.
It also refactors some member names from using the underscore `_` to camelcase notation.

Since this PR is heavily related to #94, it would suggest to merge it, after #94 is merged. Or what do you guys think?

And finally when #94 and this PR is merged, I also suggest to extract the `player` out of `me`, since they are different api contexts.

### CODE REVIEW

**Comment by rinukkusu** [comment]
LGTM from what I can tell!
Thanks for cleaning up the nasty `Player` model 😄 

And yeah, I remember some discussion from a while ago, where I also vouched for pulling out the `player` endpoint in its own class - maybe then adding it as a member to the `me` class, so you can naturally access it like so: `spotify.me.player.shuffle()`.

**Review by rinukkusu — DISMISSED** [review]

**Comment by hayribakici** [comment]
`spotify.me.player` sounds like a good solution to me. It might be a simple thing, but both `user` and `player` share the same `_get` constant. And it reflects the API better.

**Comment by hayribakici** [comment]
@hayribakici I think this can be merged.

**Comment by rinukkusu** [comment]
Sadly can not be merged as of now:
grafik

**Pull request merged**
