### PR TITLE
Add filter function to pagination logic and use it in playlists

### PR DESCRIPTION
**Pull request by Skycoder42**
This PR is a followup to the discussion in #218. It follows the second approach described there that uses a filter function instead of returning nullable track objects.

I decided to create a 2nd PR so both approaches can be discussed and evaluated before a decision will be made.

### CODE REVIEW

**Comment by rinukkusu** [comment]
Looks good - would you be willing to also add a unit test for this new feature?

**Comment by hayribakici** [comment]
That looks good so far. Could you also add a unit test for this by adding a `tracks.json` in `test/data/v1/playlists/1..F/` with some `null entries`?

**Review by rinukkusu — CHANGES_REQUESTED** [review]
Looks good from what I can tell

**Review by rinukkusu — APPROVED** [review]
Nice, thank you for helping out! LGTM

**Pull request merged**
